name: {{app_name.snakeCase()}}
description: {{app_description}}.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ************************ BASIC PACKAGES ************************ #
  cupertino_icons: 1.0.5

  # ************************ LOCAL STORAGE ************************* #
  shared_preferences: 2.2.0

  # ************************ NETWORK AND API ******************************* #
  dio: 5.3.2
  pretty_dio_logger: 1.3.1
  retrofit: 4.0.1

  # ************************ STATE MANAGEMENT ********************* #
  flutter_hooks: 0.20.0
  hooks_riverpod: 2.3.8
  rxdart: 0.27.7

  # ************************ ROUTING ****************************** #
  go_router: 10.1.0

  # ************************ ANNOTATIONS  ************************* #
  riverpod_annotation: 2.1.2
  json_annotation: 4.8.1
  freezed_annotation: 2.4.1
  json_serializable: 6.7.1

  # ************************ FORMS ********************************** #
  flutter_form_builder: 9.1.0
  form_builder_validators: 9.0.0


  # ************************* UI ********************************** #


  # ************************ UTILS ******************************** #
  intl: 0.18.1
  flutter_native_splash: 2.3.2
  cached_network_image: 3.2.3
  loading_indicator: 3.1.1




dev_dependencies:

  # ************************ GENERATORS ************************** #
  build_runner: 2.4.6
  freezed: 2.4.2
  riverpod_generator: 2.2.6
  retrofit_generator: 7.0.8

  # ************************ LINTERS ***************************** #
  flutter_lints: 2.0.2
  custom_lint: 0.5.2
  riverpod_lint: 2.0.1

  # ************************ APPLICATION ICONS ***************************** #
  flutter_launcher_icons: 0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-Bold.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Bold.ttf

# Flutter splash and icon generator

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app-icon-circle-128.png"  # 128x128
  remove_alpha_ios: true
  min_sdk_android: 21


flutter_native_splash:
  color: "#272625"
  #background_image: "assets/background.png"
  image: assets/images/app-logo.png

  android_12:
    # The image parameter sets the splash screen icon image.  If this parameter is not specified,
    # the app's launcher icon will be used instead.
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.
    image: assets/images/app-logo-android12.png

    # Splash screen background color.
    color: "#272625"